# Generated by Django 3.2.12 on 2022-05-19 11:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20220519_1128'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Admin',
        ),
        migrations.DeleteModel(
            name='ApiItem',
        ),
        migrations.DeleteModel(
            name='AuthGroup',
        ),
        migrations.DeleteModel(
            name='AuthGroupPermissions',
        ),
        migrations.DeleteModel(
            name='AuthPermission',
        ),
        migrations.DeleteModel(
            name='AuthUser',
        ),
        migrations.DeleteModel(
            name='AuthUserGroups',
        ),
        migrations.DeleteModel(
            name='AuthUserUserPermissions',
        ),
        migrations.DeleteModel(
            name='Brands',
        ),
        migrations.DeleteModel(
            name='Categories',
        ),
        migrations.DeleteModel(
            name='Creditors',
        ),
        migrations.DeleteModel(
            name='Creditpayments',
        ),
        migrations.DeleteModel(
            name='Credits',
        ),
        migrations.DeleteModel(
            name='DjangoAdminLog',
        ),
        migrations.DeleteModel(
            name='DjangoContentType',
        ),
        migrations.DeleteModel(
            name='DjangoMigrations',
        ),
        migrations.DeleteModel(
            name='DjangoSession',
        ),
        migrations.DeleteModel(
            name='Invoices',
        ),
        migrations.DeleteModel(
            name='Items',
        ),
        migrations.DeleteModel(
            name='Locations',
        ),
        migrations.DeleteModel(
            name='Payments',
        ),
        migrations.DeleteModel(
            name='Products',
        ),
        migrations.DeleteModel(
            name='ProductsRecord',
        ),
        migrations.DeleteModel(
            name='Quantities',
        ),
        migrations.DeleteModel(
            name='Sellers',
        ),
        migrations.DeleteModel(
            name='SellersSells',
        ),
        migrations.DeleteModel(
            name='Sells',
        ),
        migrations.DeleteModel(
            name='Settings',
        ),
        migrations.DeleteModel(
            name='Sizes',
        ),
        migrations.DeleteModel(
            name='StatusDemo',
        ),
    ]
