# Generated by Django 3.2.12 on 2022-05-19 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('api', '0003_auto_20220519_1129'),
    ]

    operations = [
        migrations.CreateModel(
            name='Admin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('username', models.CharField(max_length=20)),
                ('email', models.CharField(max_length=100)),
                ('password', models.CharField(max_length=100)),
                ('image', models.CharField(max_length=200)),
                ('position', models.IntegerField()),
                ('status', models.IntegerField()),
                ('androidtoken', models.CharField(blank=True, db_column='androidToken', max_length=1000, null=True)),
                ('webtoken', models.CharField(blank=True, db_column='webToken', max_length=1000, null=True)),
                ('timestamp', models.DateTimeField()),
            ],
            options={
                'db_table': 'admin',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, unique=True)),
            ],
            options={
                'db_table': 'auth_group',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthGroupPermissions',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'auth_group_permissions',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthPermission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('codename', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'auth_permission',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128)),
                ('last_login', models.DateTimeField(blank=True, null=True)),
                ('is_superuser', models.IntegerField()),
                ('username', models.CharField(max_length=150, unique=True)),
                ('first_name', models.CharField(max_length=150)),
                ('last_name', models.CharField(max_length=150)),
                ('email', models.CharField(max_length=254)),
                ('is_staff', models.IntegerField()),
                ('is_active', models.IntegerField()),
                ('date_joined', models.DateTimeField()),
            ],
            options={
                'db_table': 'auth_user',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthUserGroups',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'auth_user_groups',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthUserUserPermissions',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'auth_user_user_permissions',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Brands',
            fields=[
                ('brand_id', models.AutoField(primary_key=True, serialize=False)),
                ('brand_name', models.CharField(max_length=200)),
                ('created_at', models.DateTimeField()),
            ],
            options={
                'db_table': 'brands',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Categories',
            fields=[
                ('category_id', models.AutoField(primary_key=True, serialize=False)),
                ('category_name', models.CharField(max_length=200)),
                ('created_at', models.DateTimeField()),
            ],
            options={
                'db_table': 'categories',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Creditors',
            fields=[
                ('creditorid', models.AutoField(db_column='creditorId', primary_key=True, serialize=False)),
                ('creditorname', models.CharField(db_column='creditorName', max_length=50)),
                ('creditormobile', models.CharField(db_column='creditorMobile', max_length=15)),
                ('creditoraddress', models.CharField(db_column='creditorAddress', max_length=700)),
                ('timestamp', models.DateTimeField()),
            ],
            options={
                'db_table': 'creditors',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Creditpayments',
            fields=[
                ('paymentid', models.AutoField(db_column='paymentId', primary_key=True, serialize=False)),
                ('paymentmode', models.CharField(db_column='paymentMode', max_length=100)),
                ('paymentdate', models.DateTimeField(db_column='paymentDate')),
                ('paymentamount', models.IntegerField(db_column='paymentAmount')),
                ('paymentreciever', models.IntegerField(db_column='paymentReciever')),
                ('creditid', models.IntegerField(db_column='creditId')),
                ('creditorid', models.IntegerField(db_column='creditorId')),
                ('created_at', models.DateTimeField()),
            ],
            options={
                'db_table': 'creditpayments',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Credits',
            fields=[
                ('creditid', models.AutoField(db_column='creditId', primary_key=True, serialize=False)),
                ('creditorid', models.IntegerField(db_column='creditorId')),
                ('salesid', models.CharField(db_column='salesId', max_length=500)),
                ('creditdescription', models.CharField(db_column='creditDescription', max_length=1000)),
                ('credittime', models.DateTimeField(db_column='creditTime')),
                ('timestamp', models.DateTimeField()),
            ],
            options={
                'db_table': 'credits',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoAdminLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action_time', models.DateTimeField()),
                ('object_id', models.TextField(blank=True, null=True)),
                ('object_repr', models.CharField(max_length=200)),
                ('action_flag', models.PositiveSmallIntegerField()),
                ('change_message', models.TextField()),
            ],
            options={
                'db_table': 'django_admin_log',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoContentType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('app_label', models.CharField(max_length=100)),
                ('model', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'django_content_type',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoMigrations',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('app', models.CharField(max_length=255)),
                ('name', models.CharField(max_length=255)),
                ('applied', models.DateTimeField()),
            ],
            options={
                'db_table': 'django_migrations',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoSession',
            fields=[
                ('session_key', models.CharField(max_length=40, primary_key=True, serialize=False)),
                ('session_data', models.TextField()),
                ('expire_date', models.DateTimeField()),
            ],
            options={
                'db_table': 'django_session',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Invoices',
            fields=[
                ('invoice_id', models.AutoField(primary_key=True, serialize=False)),
                ('invoice_number', models.CharField(max_length=100)),
                ('seller_id', models.IntegerField()),
                ('invoice_date', models.DateField()),
                ('invoice_url', models.CharField(max_length=600)),
                ('total_amount', models.IntegerField()),
                ('paid_amount', models.IntegerField()),
                ('created_at', models.DateTimeField()),
            ],
            options={
                'db_table': 'invoices',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Items',
            fields=[
                ('itemid', models.AutoField(db_column='itemId', primary_key=True, serialize=False)),
                ('itemname', models.CharField(db_column='itemName', max_length=60)),
                ('itemdescription', models.CharField(db_column='itemDescription', max_length=1000)),
                ('created_at', models.DateTimeField()),
                ('updated_at', models.DateTimeField()),
            ],
            options={
                'db_table': 'items',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Locations',
            fields=[
                ('location_id', models.AutoField(primary_key=True, serialize=False)),
                ('location_name', models.CharField(max_length=200)),
                ('created_at', models.DateTimeField()),
            ],
            options={
                'db_table': 'locations',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Payments',
            fields=[
                ('payment_id', models.AutoField(primary_key=True, serialize=False)),
                ('payment_mode', models.CharField(max_length=100)),
                ('payment_date', models.DateTimeField()),
                ('payment_amount', models.IntegerField()),
                ('payment_receiver', models.IntegerField()),
                ('invoice_number', models.CharField(max_length=200)),
                ('seller_id', models.IntegerField()),
                ('created_at', models.DateTimeField()),
            ],
            options={
                'db_table': 'payments',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Products',
            fields=[
                ('product_id', models.AutoField(primary_key=True, serialize=False)),
                ('category_id', models.IntegerField()),
                ('item_id', models.IntegerField()),
                ('size_id', models.IntegerField()),
                ('brand_id', models.IntegerField()),
                ('product_price', models.IntegerField()),
                ('product_quantity', models.IntegerField()),
                ('location_id', models.IntegerField()),
                ('product_manufacture', models.DateField()),
                ('product_expire', models.DateField()),
                ('barcode', models.CharField(db_column='barCode', max_length=200)),
                ('created_at', models.DateTimeField()),
            ],
            options={
                'db_table': 'products',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ProductsRecord',
            fields=[
                ('product_id', models.AutoField(primary_key=True, serialize=False)),
                ('category_id', models.IntegerField()),
                ('item_id', models.IntegerField()),
                ('product_name', models.CharField(max_length=200)),
                ('size_id', models.IntegerField()),
                ('brand_id', models.IntegerField()),
                ('product_price', models.IntegerField()),
                ('product_quantity', models.IntegerField()),
                ('location_id', models.IntegerField()),
                ('product_manufacture', models.DateField()),
                ('product_expire', models.DateField()),
                ('created_at', models.DateTimeField()),
            ],
            options={
                'db_table': 'products_record',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Quantities',
            fields=[
                ('quantity_id', models.AutoField(primary_key=True, serialize=False)),
                ('quantity', models.IntegerField()),
                ('product_id', models.IntegerField()),
                ('size_id', models.IntegerField()),
                ('brand_id', models.IntegerField()),
                ('created_at', models.DateTimeField()),
            ],
            options={
                'db_table': 'quantities',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Sellers',
            fields=[
                ('sellerid', models.AutoField(db_column='sellerId', primary_key=True, serialize=False)),
                ('sellername', models.CharField(db_column='sellerName', max_length=50)),
                ('selleremail', models.CharField(db_column='sellerEmail', max_length=50)),
                ('sellercontact', models.CharField(db_column='sellerContact', max_length=12)),
                ('sellercontact1', models.CharField(db_column='sellerContact1', max_length=12)),
                ('sellerimage', models.CharField(db_column='sellerImage', max_length=100)),
                ('selleraddress', models.CharField(db_column='sellerAddress', max_length=1000)),
                ('createdat', models.DateTimeField(db_column='createdAt')),
            ],
            options={
                'db_table': 'sellers',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='SellersSells',
            fields=[
                ('sellers_sell_id', models.AutoField(primary_key=True, serialize=False)),
                ('seller_id', models.IntegerField()),
                ('invoice_number', models.CharField(max_length=100)),
                ('product_id', models.IntegerField()),
                ('sell_quantity', models.IntegerField()),
                ('sell_discount', models.FloatField()),
                ('sell_price', models.IntegerField()),
                ('created_at', models.DateTimeField()),
                ('updated_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'sellers_sells',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Sells',
            fields=[
                ('sell_id', models.AutoField(primary_key=True, serialize=False)),
                ('product_id', models.IntegerField()),
                ('sell_quantity', models.IntegerField()),
                ('sell_discount', models.IntegerField()),
                ('sell_price', models.IntegerField()),
                ('created_at', models.DateTimeField()),
                ('updated_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'sells',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Settings',
            fields=[
                ('settingid', models.AutoField(db_column='settingId', primary_key=True, serialize=False)),
                ('productnoticecount', models.IntegerField(db_column='productNoticeCount')),
            ],
            options={
                'db_table': 'settings',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Sizes',
            fields=[
                ('size_id', models.AutoField(primary_key=True, serialize=False)),
                ('size_name', models.CharField(max_length=200)),
                ('size_type', models.IntegerField()),
                ('created_at', models.DateTimeField()),
            ],
            options={
                'db_table': 'sizes',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='StatusDemo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('productid', models.IntegerField(db_column='productId')),
                ('timestamp', models.DateTimeField()),
            ],
            options={
                'db_table': 'status_demo',
                'managed': False,
            },
        ),
    ]
